# Generated by Django 5.1.6 on 2025-02-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
