# Generated by Django 5.1.6 on 2025-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_appointment_remove_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Haircut', 'Haircut'), ('Hair Color', 'Hair Color'), ('Beard Dressing', 'Beard Dressing'), ('Shaving', 'Shaving')], max_length=50),
        ),
    ]
